/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminEventIdRouteImport } from './routes/admin/$eventId'
import { Route as BoothEventIdRouteImport } from './routes/booth/$eventId'
import { Route as BriefEventIdRouteImport } from './routes/brief/$eventId'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalEventIdRouteImport } from './routes/portal/$eventId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventIdRoute = AdminEventIdRouteImport.update({
  id: '/admin/$eventId',
  path: '/admin/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoothEventIdRoute = BoothEventIdRouteImport.update({
  id: '/booth/$eventId',
  path: '/booth/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefEventIdRoute = BriefEventIdRouteImport.update({
  id: '/brief/$eventId',
  path: '/brief/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalEventIdRoute = PortalEventIdRouteImport.update({
  id: '/portal/$eventId',
  path: '/portal/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/$eventId': typeof AdminEventIdRoute
  '/booth/$eventId': typeof BoothEventIdRoute
  '/brief/$eventId': typeof BriefEventIdRoute
  '/portal/$eventId': typeof PortalEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/$eventId': typeof AdminEventIdRoute
  '/booth/$eventId': typeof BoothEventIdRoute
  '/brief/$eventId': typeof BriefEventIdRoute
  '/portal/$eventId': typeof PortalEventIdRoute
  '/admin': typeof AdminIndexRoute
  '/portal': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/$eventId': typeof AdminEventIdRoute
  '/booth/$eventId': typeof BoothEventIdRoute
  '/brief/$eventId': typeof BriefEventIdRoute
  '/portal/$eventId': typeof PortalEventIdRoute
  '/admin/': typeof AdminIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/$eventId'
    | '/booth/$eventId'
    | '/brief/$eventId'
    | '/portal/$eventId'
    | '/admin/'
    | '/portal/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/$eventId'
    | '/booth/$eventId'
    | '/brief/$eventId'
    | '/portal/$eventId'
    | '/admin'
    | '/portal'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/$eventId'
    | '/booth/$eventId'
    | '/brief/$eventId'
    | '/portal/$eventId'
    | '/admin/'
    | '/portal/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminEventIdRoute: typeof AdminEventIdRoute
  BoothEventIdRoute: typeof BoothEventIdRoute
  BriefEventIdRoute: typeof BriefEventIdRoute
  PortalEventIdRoute: typeof PortalEventIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PortalIndexRoute: typeof PortalIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$eventId': {
      id: '/admin/$eventId'
      path: '/admin/$eventId'
      fullPath: '/admin/$eventId'
      preLoaderRoute: typeof AdminEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booth/$eventId': {
      id: '/booth/$eventId'
      path: '/booth/$eventId'
      fullPath: '/booth/$eventId'
      preLoaderRoute: typeof BoothEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/$eventId': {
      id: '/brief/$eventId'
      path: '/brief/$eventId'
      fullPath: '/brief/$eventId'
      preLoaderRoute: typeof BriefEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$eventId': {
      id: '/portal/$eventId'
      path: '/portal/$eventId'
      fullPath: '/portal/$eventId'
      preLoaderRoute: typeof PortalEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminEventIdRoute: AdminEventIdRoute,
  BoothEventIdRoute: BoothEventIdRoute,
  BriefEventIdRoute: BriefEventIdRoute,
  PortalEventIdRoute: PortalEventIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  PortalIndexRoute: PortalIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
